name: auto_size_text
description: Flutter widget that automatically resizes text to fit perfectly within its bounds.
version: 3.0.0
homepage: https://github.com/leisim/auto_size_text

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: '>=1.8.2 <2.0.0'